early_access: true
reviews:
  profile: "assertive"
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  tools:
    actionlint:
      enabled: false
    languagetool:
      enabled: false
    biome:
      enabled: true
    semgrep:
      enabled: false
    yamllint:
      enabled: false
chat:
  auto_reply: true







